
mybatis:
    type-aliases-package: com.ggg.bs.model
    mapper-locations: classpath*:mapper/*Mapper.xml
server:
    port: ${PORT4}
spring:
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
    datasource:
        url: ${MYSQLURL}
        username: ${MYSQLUSER}
        password: ${MYSQLPASSWORD}
        bySearch:
            testWhileIdle: true
            validationQuery: SELECT 1
            timeBestweenEvictionRunsMillis: 3600000 #每个小时确认连接是否可用
    servlet:
         multipart:
             max-file-size: 10MB
             max-request-size: 10MB

